# Generated by Django 4.2.3 on 2023-09-07 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2023, 9, 15, 15, 35, 10, 993557))),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('remarks_on_issue', models.CharField(max_length=100)),
                ('remarks_on_return', models.CharField(max_length=100)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Borrowing',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='book_issue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.students'),
        ),
    ]
