# Generated by Django 4.2.3 on 2023-09-07 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_issue_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 16, 45, 34, 888401)),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
