# Generated by Django 4.2.3 on 2023-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_issue_due_date_alter_bookinstance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_issue',
            name='date_returned',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
